### ISSUE TITLE
Trung - Assessment #10

### ISSUE THREAD

**Issue by longhypepoly** [hypepoly-internship-2022/quoc-trung-assessment-10#1]

**Comment by longhypepoly** [comment]
* Em điều chỉnh lại thời gian nhé, hiện tại thời gian idle và active của enemy và player chưa đúng như yêu cầu.
* Em điều chỉnh lại tốc độ của cube, hiện tại anh kéo 1 phát tới đích luôn, em limit nó lại sao cho mỗi lần kéo thì chỉ chạy được tối đa 1/4 màn hình thôi 😂

**Comment by quoctrungvu1610** [comment]
Dạ anh Long

**Comment by longhypepoly** [comment]
Good job em 💯
